# Generated by Django 5.1.4 on 2025-01-16 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='loginid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='learner.logintable'),
            preserve_default=False,
        ),
    ]
