# Generated by Django 5.1.4 on 2025-01-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_studentregistration_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='StudentContact',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='StudentId',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
