# Generated by Django 5.1.4 on 2025-01-17 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0003_studentregistration_studentcontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.logintable')),
            ],
        ),
    ]
