# Generated by Django 5.1.4 on 2025-01-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0004_userregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='usertype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
