# Generated by Django 5.1.4 on 2025-02-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0006_mentors'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
