# Generated by Django 5.1.4 on 2025-02-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0007_logintable_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintable',
            name='status',
        ),
    ]
