# Generated by Django 5.1.4 on 2025-02-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0008_remove_logintable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
