# Generated by Django 5.1.4 on 2025-02-01 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0009_mentors_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=10)),
                ('Reg_id', models.CharField(max_length=40)),
                ('loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learner.logintable')),
            ],
        ),
    ]
