# Generated by Django 5.1.4 on 2025-02-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0010_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
