# Generated by Django 5.1.4 on 2025-02-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0011_alter_mentors_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
