# Generated by Django 5.1.4 on 2025-02-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0012_company_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_category', models.CharField(max_length=40)),
                ('Job_name', models.CharField(max_length=40)),
                ('Job_description', models.CharField(max_length=40)),
                ('Job_qualification', models.CharField(max_length=40)),
                ('Apply_before', models.DateField()),
            ],
        ),
    ]
