# Generated by Django 5.1.4 on 2025-02-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0013_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Job_description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_qualification',
            field=models.CharField(max_length=100),
        ),
    ]
