# Generated by Django 5.1.4 on 2025-02-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0014_alter_job_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Company_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
