# Generated by Django 5.1.4 on 2025-02-02 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0015_job_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.company'),
        ),
    ]
