# Generated by Django 5.1.4 on 2025-02-07 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0016_alter_job_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume', models.FileField(upload_to='Cadresume/')),
                ('Job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.job')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.logintable')),
            ],
        ),
    ]
