# Generated by Django 5.1.4 on 2025-02-07 05:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0017_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='Current_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
