# Generated by Django 5.1.4 on 2025-02-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0018_jobapplication_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
