# Generated by Django 5.1.4 on 2025-02-13 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0019_jobapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoconference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('Mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.mentors')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.studentregistration')),
            ],
        ),
    ]
