# Generated by Django 5.1.4 on 2025-02-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0020_videoconference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='videoconference',
            new_name='mentorclass',
        ),
    ]
