# Generated by Django 5.1.4 on 2025-02-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0021_rename_videoconference_mentorclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorclass',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.logintable'),
        ),
    ]
