# Generated by Django 5.1.4 on 2025-02-27 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0022_alter_mentorclass_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='loginid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learner.logintable'),
        ),
    ]
