# Generated by Django 5.1.4 on 2025-02-27 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0023_alter_studentregistration_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='loginid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='learner.logintable'),
        ),
    ]
