# Generated by Django 5.1.4 on 2025-02-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0024_alter_studentregistration_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorclass',
            name='cancel',
            field=models.IntegerField(default=0),
        ),
    ]
