# Generated by Django 5.1.4 on 2025-02-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0025_mentorclass_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorclass',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
